# H2 adatbázis beállítások
spring.datasource.url=jdbc:h2:mem:sokobandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate beállítások (automatikusan frissíti a táblákat az osztályok alapján)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 webes konzol engedélyezése
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console